# Generated by Django 2.2.1 on 2019-06-08 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to='images/category/')),
                ('completeMessage', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Earth',
            fields=[
                ('earthLevel', models.IntegerField(choices=[(1, 'Earth level 1'), (2, 'Earth level 2'), (3, 'Earth level 3'), (4, 'Earth level 4'), (5, 'Earth level 5'), (6, 'Earth level 6'), (7, 'Earth level 7'), (8, 'Earth level 8')], primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to='images/earth/')),
                ('content', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'earth',
                'verbose_name_plural': 'earth',
                'db_table': 'earth',
            },
        ),
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('image', models.FileField(upload_to='images/prefer/')),
                ('selectImage', models.FileField(upload_to='images/prefer/')),
            ],
            options={
                'verbose_name': 'prefer',
                'verbose_name_plural': 'prefers',
                'db_table': 'prefers',
            },
        ),
        migrations.CreateModel(
            name='UserPrefer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Prefer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/mission/')),
                ('title', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
                ('missionTipTitle', models.CharField(max_length=50)),
                ('missionTipContent', models.CharField(max_length=256)),
                ('missionMethodContent', models.CharField(max_length=256)),
                ('missionEffectContent', models.CharField(max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
            options={
                'verbose_name': 'mission',
                'verbose_name_plural': 'missions',
                'db_table': 'missions',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(choices=[(1, 'Mission RESULT 0'), (1, 'Mission RESULT 1'), (2, 'Mission RESULT 2'), (3, 'Mission RESULT 3'), (4, 'Mission RESULT 4'), (5, 'Mission RESULT 5')], default=0)),
                ('message', models.CharField(default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feed',
                'verbose_name_plural': 'feeds',
                'db_table': 'feeds',
                'ordering': ('created',),
            },
        ),
    ]
