# Generated by Django 2.2.1 on 2019-05-18 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(default='dafault/default_image.png', upload_to='images/')),
            ],
            options={
                'verbose_name': 'prefer',
                'verbose_name_plural': 'prefers',
                'db_table': 'prefers',
            },
        ),
    ]
