# Generated by Django 2.2.1 on 2019-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earth',
            fields=[
                ('earthLevel', models.IntegerField(choices=[(1, 'Earth level 1'), (2, 'Earth level 2'), (3, 'Earth level 3'), (4, 'Earth level 4'), (5, 'Earth level 5'), (6, 'Earth level 6'), (7, 'Earth level 7'), (8, 'Earth level 8')], primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='images/earth/')),
                ('content', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'earth',
                'verbose_name_plural': 'earth',
                'db_table': 'earth',
            },
        ),
    ]
