# Generated by Django 2.2.2 on 2019-06-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='images/donation/')),
                ('link', models.URLField(max_length=256)),
            ],
            options={
                'verbose_name': 'donation',
                'verbose_name_plural': 'donations',
                'db_table': 'donations',
            },
        ),
    ]
