# Generated by Django 2.2.1 on 2019-05-21 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/mission/')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=256)),
                ('missionTipTitle', models.CharField(max_length=50)),
                ('missionTipContent', models.CharField(max_length=256)),
                ('missionMethodTitle', models.CharField(max_length=50)),
                ('missionMethodContent', models.CharField(max_length=256)),
                ('missionEffectTitle', models.CharField(max_length=50)),
                ('missionEffectContent', models.CharField(max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
            options={
                'verbose_name': 'mission',
                'verbose_name_plural': 'missions',
                'db_table': 'missions',
            },
        ),
    ]
