# Generated by Django 2.2.2 on 2019-06-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprefer',
            name='prefer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Prefer'),
        ),
    ]
